from argparse import Namespace

param_sim = Namespace(calcium=None,
                      hsolve=True,
                      injection_current=None,
                      injection_delay=0.1,
                      injection_width=0.4,
                      modelParamOverrides=None,
                      plot_activation=None,
                      plot_calcium=True,
                      plot_channels=None,
                      plot_current=None,
                      plot_current_label='Cond, S',
                      plot_current_message='getGk',
                      plot_netvm=None,
                      plot_network=None,
                      plot_synapse=None,
                      plot_synapse_label='Cond, nS',
                      plot_synapse_message='getGk',
                      plot_vm=True,
                      plotdt=0.0002,
                      save=None,
                      simdt=1e-05,
                      simtime=0.35,
                      spines=None,
                      stim_loc=None,
                      stim_paradigm=None,
                      synapse=None)
